version: '3.9'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapp
    restart: unless-stopped
    volumes:
      - /var/run/flaskapp:/var/run/flaskapp
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT:-80}:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/sites-available:/etc/nginx/sites-available
      - ./configs/nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - flaskapp
      - apache2
    networks:
      - frontend
      - backend

  apache2:
    image: httpd:latest
    container_name: apache2
    restart: unless-stopped
    volumes:
      - ./configs/apache2/apache.conf:/usr/local/apache2/conf/httpd.conf
      - ./configs/apache2/sites-available:/usr/local/apache2/conf/sites-available
    depends_on:
      - flaskapp
    networks:
      - backend

  ssh:
    image: linuxserver/openssh-server
    container_name: ssh
    restart: unless-stopped
    ports:
      - "${SSH_PORT:-22}:22"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - frontend

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge